config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  root "home#index"
  resources :books

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  namespace :admin do
    resources :categories, only: [:index, :new, :create, :destroy]
    resources :users
  end
end

app/models/category.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: categories
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_categories_on_name  (name) UNIQUE
#
class Category < ApplicationRecord
  has_many :books, dependent: :destroy

  scope :ordered_by_name, -> { order(:name) }

  validates :name, presence: true, uniqueness: true
end

app/controllers/admin/categories_controller.rb
# frozen_string_literal: true

module Admin
  class CategoriesController < ApplicationController
    before_action :authenticate_user!
    after_action :verify_authorized, except: :index

    def index
      @categories = Category.all
      authorize @categories
    end

    def new
      @category = Category.new
      authorize @category
    end

    def create
      @category = Category.new(category_params)
      authorize @category

      if @category.save
        redirect_to admin_categories_path, notice: "Category was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end

    def destroy
      @category = Category.find(params[:id])
      authorize @category

      @category.destroy
      redirect_to admin_categories_path, notice: "Category was successfully deleted."
    end

    private
    def category_params
      params.require(:category).permit(:name)
    end
  end
end

app/views/admin/categories/index.html.erb
<div class="container mx-auto px-4">
  <h1 class="text-center text-3xl font-semibold my-6">Categories</h1>

  <%= link_to 'New Category', new_admin_category_path, class: 'bg-blue-500 text-white py-2 px-6 rounded-lg mb-6 inline-block max-w-fit hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-300' %>

  <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
    <% @categories.each do |category| %>
      <div class="bg-white border border-gray-200 rounded-lg shadow-md p-6 flex flex-col items-start">
        <h3 class="text-xl font-semibold text-gray-800 mb-4"><%= category.name %></h3>

        <div class="flex space-x-2">
          <%= link_to 'Edit', class: 'bg-yellow-500 text-white py-2 px-4 rounded-lg hover:bg-yellow-600 focus:outline-none focus:ring-2 focus:ring-yellow-300' %>
          <%= button_to 'Delete', admin_category_path(category), method: :delete, data: { confirm: 'Are you sure you want to delete this category?' }, class: 'bg-red-500 text-white py-2 px-4 rounded-lg hover:bg-red-600 focus:outline-none focus:ring-2 focus:ring-red-300' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/categories/new.html.erb
<div class="max-w-max mx-auto">
  <h2 class="text-3xl font-bold mb-4">Create New Category</h2>

  <div class="bg-white border border-[#E2E4E5] rounded-md shadow-md p-8">
    <%= form_with(model: @category, url: admin_categories_path, local: true, class: "space-y-4") do |f| %>
      <div class="space-y-2">
        <div class="input-wrapper">
          <%= f.label :name, "Category Name", class: "text-gray-700 font-medium" %>
          <%= f.text_field :name, class: "input-custom w-full p-3 border border-gray-300 rounded-md focus:ring-blue-500 focus:outline-none" %>
        </div>
        <% if @category.errors.any? %>
          <div class="text-red-500 text-sm mt-1">
            <ul class="list-disc list-inside">
              <% @category.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
      </div>

      <div class="mb-4">
        <%= f.submit "Create Category", class: "px-8 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors mr-4" %>
      </div>
    <% end %>
  </div>

  <div class="text-center mt-6">
    <%= link_to "Back to Categories", admin_categories_path, class: "inline-block py-2 px-4 bg-gray-300 text-gray-700 rounded-md hover:bg-gray-400 focus:ring-2 focus:ring-gray-200 focus:outline-none transition duration-150" %>
  </div>
</div>