config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  root "home#index"
  resources :books

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  namespace :admin do
    resources :categories, only: [:index, :new, :create, :destroy]
    resources :users
  end
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  birthdate              :date             not null
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  first_name             :string           not null
#  last_name              :string           not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  role                   :string           default("user")
#  username               :string           not null
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#  index_users_on_username              (username) UNIQUE
#
class User < ApplicationRecord
  ROLES = %w[user admin moderator].freeze

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :username, presence: true, uniqueness: true
  validates :birthdate, presence: true
  validates :role, inclusion: { in: ROLES }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  scope :sorted_by_first_name, -> { order(:first_name) }

  def admin?
    role == "admin"
  end

  def moderator?
    role == "moderator"
  end

  def user?
    role == "user"
  end
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

# app/controllers/admin/users_controller.rb
module Admin
  class UsersController < ApplicationController
    before_action :authenticate_user!
    before_action :set_user, only: %i[show edit update destroy]
    after_action :verify_authorized

    def index
      @users = policy_scope(User).sorted_by_first_name
      authorize User
    end

    def show
      authorize @user
    end

    def new
      @user = User.new
      authorize @user
    end

    def create
      @user = User.new(user_params)
      authorize @user
      @user.password = generate_random_password if @user.password.blank?

      if @user.save
        redirect_to admin_user_path(@user), notice: "User was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end

    def edit
      authorize @user
    end

    def update
      authorize @user
      if @user.update_without_password(user_params)
        redirect_to admin_user_path(@user), notice: "User was successfully updated."
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      authorize @user
      @user.destroy
      redirect_to admin_users_path, notice: "User was successfully deleted."
    end

    private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :username, :birthdate, :role, :password,
                                   :password_confirmation)
    end

    def generate_random_password
      SecureRandom.hex(6)
    end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

module Users
  class RegistrationsController < Devise::RegistrationsController
    before_action :configure_sign_up_params, only: [:create]

    def configure_sign_up_params
      devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name birthdate username email])
    end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

module Users
  class SessionsController < Devise::SessionsController
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_with model: @user, url: @user.new_record? ? admin_users_path : admin_user_path(@user), method: @user.new_record? ? :post : :patch, local: true, data: { turbo: false }, class: 'space-y-4' do |f| %>
  <div class="grid grid-cols-2 gap-4">
    <% fields = [
      { name: :first_name, label: "First Name", additional_classes: "", type: :text_field },
      { name: :last_name, label: "Last Name", additional_classes: "", type: :text_field },
      { name: :username, label: "Username", additional_classes: "", type: :text_field },
      { name: :email, label: "Enter email", additional_classes: "", type: :text_field },
      { name: :birthdate, label: "Date of Birth", additional_classes: "datepicker", type: :text_field },
      { name: :role, label: "Role", type: :select, additional_classes: "", options: User::ROLES.map { |role| [role.humanize, role] } }
    ] %>

    <% fields.each do |field| %>
      <div class="space-y-2 mb-4">
        <div class="input-wrapper">
          <%= f.label field[:name], field[:label], class: "text-gray-700 font-medium" %>
          <% if field[:type] == :select %>
            <%= f.select field[:name], field[:options], { prompt: "Select a #{field[:label]}" }, class: "input-custom #{field[:additional_classes]}" %>
          <% else %>
            <%= f.public_send(field[:type], field[:name], class: "input-custom #{field[:additional_classes]}") %>
          <% end %>
        </div>
        <% if f.object.errors[field[:name]].any? %>
          <div class="text-red-500 text-sm mt-1">
            <%= f.object.errors[field[:name]].join(", ") %>
          </div>
        <% end %>
      </div>
    <% end %>

    <div class="mb-4">
      <%= f.submit @user.new_record? ? 'Create User' : 'Update User', class: "px-8 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors mr-4" %>
    </div>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<div class="max-w-max mx-auto">
  <h2 class="text-3xl font-bold mb-4">Edit User</h2>
  <div class="bg-white border border-[#E2E4E5] rounded-md shadow-md p-8">
    <%= render 'form', user: @user %>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container mx-auto mt-12 px-4">
  <h1 class="text-3xl font-bold text-center mb-6">Users</h1>

  <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
    <% @users.each do |user| %>
      <div class="p-6 border border-gray-300 rounded-lg shadow-sm flex flex-col justify-between">
        <div>
          <h2 class="text-lg font-semibold mb-2"><%= user.first_name %> <%= user.last_name %></h2>
          <p class="text-sm text-gray-600 mb-1">Email: <%= user.email %></p>
          <p class="text-sm text-gray-600">Username: <%= user.username %></p>
        </div>
        <div class="mt-4 flex justify-between">
          <%= link_to 'View', admin_user_path(user), class: 'text-blue-500 hover:underline' %>
          <%= link_to 'Edit', edit_admin_user_path(user), class: 'text-green-500 hover:underline' %>
          <%= link_to 'Delete', admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' }, class: 'text-red-500 hover:underline' %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="text-center mt-8">
    <%= link_to 'Create New User', new_admin_user_path, class: 'px-4 py-2 bg-green-500 text-white rounded-lg shadow hover:bg-green-600' %>
  </div>
</div>

app/views/admin/users/new.html.erb
<div class="max-w-max mx-auto">
  <h2 class="text-3xl font-bold mb-4">Create New User</h2>
  <div class="bg-white border border-[#E2E4E5] rounded-md shadow-md p-8">
    <%= render 'form', user: @user %>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container mx-auto mt-12 px-4 max-w-lg">
  <h1 class="text-3xl font-bold text-center mb-6">User Details</h1>

  <div class="p-6 border border-gray-300 rounded-lg shadow-sm">
    <h2 class="text-lg font-semibold mb-2"><%= @user.first_name %> <%= @user.last_name %></h2>
    <p class="text-sm text-gray-600 mb-1">Email: <%= @user.email %></p>
    <p class="text-sm text-gray-600 mb-1">Username: <%= @user.username %></p>
    <p class="text-sm text-gray-600">Role: <%= @user.role %></p>
  </div>

  <div class="mt-6 flex justify-between">
    <%= link_to 'Edit', edit_admin_user_path(@user), class: 'px-4 py-2 bg-blue-500 text-white rounded-lg shadow hover:bg-blue-600' %>
    <%= link_to 'Back', admin_users_path, class: 'px-4 py-2 bg-gray-500 text-white rounded-lg shadow hover:bg-gray-600' %>
  </div>
</div>